server:
  port: 8081
  context-path: /easy-parking

security:
  user:
    name: admin
    password: admin

spring:
  datasource: # Database properties
    url: jdbc:h2:./.tmp/easy_parking_db
    sql-script-encoding: utf-8
    username: sa
    password:
#    data: classpath:/load-test-data.sql
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect